import { Injectable, isDevMode } from '@angular/core';
import { GCPsDescriptor, TxtDescriptor, GCP, ImageGcp, Projection, ElevationMeasureUnit } from './gcps-utils.service';
import { base64ArrayBuffer } from 'src/shared/utils';
import { validate, LicenseInfo, DemoLicense, DevLicense } from './licenser';
import exifr from 'exifr';
import { GPSCoords } from '../shared/common';

@Injectable({
    providedIn: 'root'
})
export class StorageService {

    public gcps: GCP[];
    public imageGcps: ImageGcp[] = [];
    public projection: Projection;
    public images: ImageInfo[] = [];
    public license: LicenseInfo;
    public prevNames: object = {};
    /** True when the loaded gcp_list.txt was generated by the pipeline (has confidence column). */
    public hasPipelineEstimates: boolean = false;
    /** Original filename of the loaded .txt file, used to derive export filename. */
    public inputFileName: string = '';
    /** Saved scroll position of the GCP list, restored after returning from tagging. */
    public gcpListScrollTop: number = 0;

    public saveImage(image: ImageInfo): ImageInfo {
        const match = this.images.filter(item => item.name === image.name);
        if (match.length === 0) {
            this.images.push(image);
        } else {
            match[0].url = image.url;
        }
        return image;
    }

    public removeImage(imageName: string): void {
        const match = this.images.find(item => item.name === imageName);
        if (match) {
            this.images.splice(this.images.indexOf(match), 1);
        }

        this.imageGcps = this.imageGcps.filter(item => item.imgName !== imageName);
    }

    public saveImageRaw(f: File, imageUrl: string): ImageInfo {
        const image: ImageInfo = new ImageInfo(f, imageUrl);
        return this.saveImage(image);
    }

    public getImageUrl(name: string): string {
        const match = this.images.filter(item => item.name === name);

        if (match.length === 0) {
            return null;
        } else {
            return match[0].url;
        }
    }

    public hasLicense(): boolean {
        return (!!localStorage.getItem("license") && !this.getLicense().demo) || this.getLicense().dev;
    }

    public getLicense(): LicenseInfo {
        // return new DevLicense(); 
        
        if (!this.license) {
            const licstr = localStorage.getItem("license") || "";
            this.license = validate('gcpeditorpro', licstr);
        }

        if (!this.license) {
            this.license = new DemoLicense();
        }

        return this.license;
    }

    public saveLicense(license: string) {
        if (!validate('gcpeditorpro', license).demo) {
            this.license = null;
            localStorage.setItem("license", license);
        }
    }

    constructor() { }
}

class ImageInfo {

    constructor(file: File, url: string) {
        this.name = file.name;
        this.url = url;
        this._file = file;
    }

    public name: string;
    public url: string | null;
    private _coords: GPSCoords;
    private _orientation: { yaw: number | null; pitch: number | null } | undefined = undefined;
    private _file: File;

    public getCoords() : Promise<GPSCoords> {

        if (this._coords)
            return Promise.resolve(this._coords);
        
        const prom = new Promise<GPSCoords>(async (resolve, reject) => {
            try{
                let {latitude, longitude } = await exifr.gps(this.url);
                this._coords = {
                    lat: latitude,
                    lng: longitude,
                    alt: 0
                }; 
                resolve(this._coords);
            }catch(e){
                resolve(null);
            }
        });

        return prom;

    }

    public getOrientation(): Promise<{ yaw: number | null; pitch: number | null }> {
        if (this._orientation !== undefined) return Promise.resolve(this._orientation);
        return exifr.parse(this._file, { xmp: true })
            .then((result: any) => {
                const yaw = result?.GimbalYawDegree ?? result?.FlightYawDegree;
                const p = result?.GimbalPitchDegree;
                this._orientation = {
                    yaw: typeof yaw === 'number' ? yaw : null,
                    pitch: typeof p === 'number' ? p : null,
                };
                return this._orientation;
            })
            .catch(() => { this._orientation = { yaw: null, pitch: null }; return this._orientation; });
    }
}


